In [1]:
# Importación de librerías
import pandas as pd
import numpy as np
# Configuración para visualizar todas las columnas del DataFrame
pd.set_option('display.max_columns', None)

# Gestión de warnings
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Carga de datos
df = pd.read_csv("files/calidad_vida.csv")

In [ ]:
# Visualización de las primeras filas del DataFrame
df.head()

,estudio,FechaInicio,HoraInicio,FechaFin,HoraFin,Duración,NúmeroEntrevista,DISTRITO,(P0B*R1AE) - Sexo (anotar),(P0D*R1AS) - ¿Me puede decir su edad?,"P0F*R1AS) - Actualmente, ¿está viviendo en...?",(P1*M1AS) - a - En Madrid,(P1*M1AS) - b - En su distrito,(P1*M1AS) - c - En su barrio,(P2*M10S) - a - En Madrid,(P2*M10S) - b - En su distrito,(P2*M10S) - c - En su barrio,(P3*M10S) - a - En Madrid,(P3*M10S) - b - En su distrito,(P3*M10S) - c - En su barrio,(P4*M10S) - a - Cuidado y conservación de la ciudad,(P4*M10S) - b - Movilidad y transporte público,(P4*M10S) - c - Calidad medioambiental,(P4*M10S) - d - Facilidad para encontrar un trabajo,(P4*M10S) - e - Facilidad para emprender un negocio,(P4*M10S) - f - Imagen internacional de Madrid,(P4*M10S) - g - Coste de la vida,(P4*M10S) - h - Integración social,(P4*M10S) - i - Salud y servicios sanitarios,(P4*M10S) - j - Educación y centros educativos,(P4*M10S) - k - Facilidad para encontrar una vivienda en el marco de sus posibilidades,(P4*M10S) - l - Facilidad para hacer deporte,"(P4*M10S) - m - Oferta cultural, ocio y diversión",(P4*M10S) - n - Convivencia vecinal,(P4*M10S) - o - Seguridad,"(P5A*R1AE) - ¿Cuáles son, a su juicio y por orden de prioridad, los tres problemas principales que existen actualmente en la ciudad de Madrid? (anotar 1ª problema)",(P5B*R1AE) - Anotar 2ª problema,(P5C*R1AE) - Anotar 3ª problema,P4_Total,(P6*M10S) - a - Desigualdad de oportunidades entre hombres y mujeres,(P6*M10S) - b - Desigualdad de oportunidades entre la población extranjera y autóctona,(P7*M10S) - a - Las personas mayores,(P7*M10S) - b - La infancia,(P7*M10S) - c - Las personas con discapacidad,(P7*M10S) - d - Las personas lgtbiq+,(P7*M10S) - e - Los migrantes,(7*M10S) - f - La adolescencia,(P8*M10S) - a - La recogida de basuras y contenedores,"(P8*M10S) - b - La gestión y tratamiento de residuos (reciclaje, compostaje, etc.)",(P8*M10S) - c - El control de la contaminación atmosférica,(P8*M10S) - d - El control del ruido,(P8*M10S) - e - La limpieza de las calles,(P8*M10S) - f - El alumbrado público,"(P8*M10S) - g - Las infraestructuras de la ciudad para la circulación de vehículos (calles, túneles, etc.…)",(P8*M10S) - h - La pavimentación y conservación de las aceras,(P8*M10S) - i - El asfaltado y conservación de las calzadas,(P8*M10S) - j - La peatonalización de calles,"(P8*M10S) - k - La eliminación de barreras arquitectónicas (rebaje de bordillos, semáforos acústicos, etc.)",(P8*M10S) - l - La movilidad sostenible,(P8*M10S) - v - La mejora de la calidad del aire,(P8*M10S) - m - La conservación y rehabilitación de los edificios,(P8*M10S) - n - La protección de monumentos y del patrimonio histórico-artístico,(P8*M10S) - o - La información y promoción turística,"(P8*M10S) - p - La organización de fiestas y eventos populares (cabalgata, fiestas de san isidro, fiestas de los distritos...)","(P8*M10S) - q - El control de la salud pública (plagas, alimentos, aguas...)",(P8*M10S) - r - Las ayudas e incentivos a pymes y autónomos,(P8*M10S) - s - La información al consumidor,(P8*M10S) - t - La promoción pública de viviendas,(P8*M10S) - w - La actuación frente a la ocupación ilegal,"(P8*M10S) - u - Los beneficios fiscales promovidos por el ayuntamiento (bajada de impuestos, bonificaciones...)",(P8*M10S) - x - El plan de fomento de la natalidad y la conciliación (el cheque bebé),(P9*M10S) - a - La atención a la ciudadanía,(P9*M10S) - c - El servicio de autobuses de la Emt,(P9*M10S) - d - Los taxis,(P9*M10S) - e - El ser (servicio de estacionamiento regulado),(P9*M10S) - f - Los agentes de movilidad,(P9*M10S) - g - La policía municipal,(P9*M10S) - h - Los bomberos,(P9*M10S) - i - Samur – protección civil,(P9*M10S) - j - La beca infantil para la escolarización 0-3 años,"(P9*M10S) - k - Los servicios sociales municipales (mayores, personas con discapacidad, inmigrantes, familias, …)",(P9*M10S) - l - Las vías ciclistas,(P9*M10S) - m - Los aparcamientos municipales,(P9*M10S) - n - Los puntos limpios de recogida y reciclaje de residuos,(P9*M10S) - o - Los espacios verdes (parques y jardines),(P9*M10S) - p - Los parques infantiles,(P9*M10S) - q - Los mercados municipales,(P9*M10S) - r - Las instalaciones deportivas municipales,(P9*M10S) - s - Los centros culturales municipales,(P9*M10S) - t - Las bibliotecas municipales,"(P9*M10S) - u - Los teatros municipales (Español, Matadero, Fernán Gómez…)",(P9*M10S) - v - El Samur social,(P9*M10S) - w - Bicimad,"(P10*R2AS) - Hablemos a continuación de cuestiones relativas a la movilidad y la seguridad en la ciudad ¿qué medio o medios de transporte utiliza habitualmente para sus desplazamientos cotidianos (desplazamientos al lugar de trabajo, estudio u otros co",Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,(P11*M10S) - b - Durante el día,(P11*M10S) - c - Durante la noche,(P11*M10S) - a - Y en general,(P12*M10S) - b - Durante el día,(P12*M10S) - c - Durante la noche,(P13*M10S) - b - Durante el día,(P13*M10S) - c - Durante la noche,"(P14*R10S) - Trataremos a continuación de la administración y el gobierno del ayuntamiento de Madrid en la misma escala, ¿en qué medida se considera usted informado/a de lo que hace el ayuntamiento de Madrid?",(P15*M10S) - a - Las oficinas de atención a la ciudadanía de línea Madrid,(P15*M10S) - b - El teléfono 010,(P15*M10S) - c - La web del ayuntamiento de Madrid: www.madrid.es,"(P15*M10S) - d - Aplicaciones del ayuntamiento para dispositivos móviles (app para móviles, Madrid móvil, emt Madrid…)",(P15*M10S) - e - Las oficinas de atención al contribuyente,(P15*M10S) - f - Chat on line de línea Madrid,"(P15*M10S) - g - Atención directa a las personas mayores, con número preferente y atención presencial sin cita previa",(P16*M10S) - a - Administración general del estado,(P16*M10S) - b - Administración de la comunidad de Madrid,(P16*M10S) - c - Administración del ayuntamiento de Madrid,"(P17*R10S) - ¿Y en términos generales, en una escala de 0 a 10 ¿cómo calificaría usted la gestión que está realizando el equipo de gobierno del ayuntamiento de Madrid?","(P18*R10S) - En una escala de 0 a 10, ¿cómo está de satisfecho/a con la administración del ayuntamiento de Madrid?",(P19*R10S) - Poniendo en relación los impuestos que paga al ayuntamiento y los servicios que recibe. En una escala de 0 a 10 ¿cómo de satisfecho/a está?,(P20*M2AS) - a - Primero,(P20*M2AS) - b - Segundo,"(P21*R1AS) - Y para terminar, a efectos de analísis estadístico, voy a hacerle algunas preguntas. ¿Podría indicarme su nacionalidad?",(P22*R1AE) - ¿Cuáles son los estudios de más alto nivel oficial que usted ha cursado (con independencia de que los haya terminado o no)?,(P23*R1AS) - ¿En cuál de las siguientes situaciones se encuentra usted actualmente? situación principal.,(P24*R1AE) - ¿Y podría decirme a qué partido o coalición votó en las elecciones municipales de mayo de 2023?,Ponderacion
0,10409_CAL_VIDA_25Dist,19-sep-25,13:28:13,19-sep-25,13:43:06,0:14:53,1449659,2,1,1,1,9,9,9,8,8,9,8,9,10,8,10,9,8,99,9,5,8,8,8,4,10,10,7,9,4.0,97.0,99.0,4;97;99,7.0,7.0,8.0,8.0,7.0,8.0,7.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,9.0,7.0,8.0,8.0,7.0,8.0,7.0,7.0,8.0,8.0,7.0,7.0,9.0,9.0,5.0,8.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,3.0,4.0,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,8.0,8.0,6.0,5.0,NaN,NaN,NaN,1,6,1,10,"1,236126"
1,10409_CAL_VIDA_25Dist,19-sep-25,13:29:37,19-sep-25,13:44:01,0:14:24,1449660,4,1,4,1,10,9,10,9,9,9,10,10,10,8,10,7,9,9,10,7,8,8,8,7,9,10,7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,10.0,8.0,9.0,8.0,8.0,10.0,9.0,9.0,8.0,7.0,9.0,9.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,9.0,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,7.0,8.0,9.0,9.0,9.0,9.0,9.0,9.0,10.0,9.0,10.0,9.0,99.0,10.0,NaN,NaN,NaN,NaN,NaN,9.0,7.0,6.0,1,6,1,1,"0,787242"
2,10409_CAL_VIDA_25Dist,19-sep-25,13:29:50,19-sep-25,13:44:29,0:14:39,1449661,8,1,3,4,9,8,9,8,7,8,7,8,9,5,7,5,5,5,8,5,7,5,7,2,7,8,7,7,4.0,8.0,10.0,4;8;10,7.0,7.0,5.0,5.0,5.0,7.0,5.0,8.0,6.0,5.0,5.0,5.0,5.0,5.0,6.0,2.0,2.0,5.0,5.0,5.0,5.0,5.0,7.0,8.0,7.0,5.0,6.0,8.0,2.0,2.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,5.0,6.0,7.0,8.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,5.0,4.0,6.0,6.0,NaN,NaN,NaN,1,6,1,7,"1,270241"
3,10409_CAL_VIDA_25Dist,19-sep-25,13:29:52,19-sep-25,13:44:18,0:14:26,1449662,5,1,3,4,7,7,8,7,7,7,6,9,8,7,8,6,7,6,8,9,7,7,7,7,7,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,6.0,8.0,7.0,8.0,7.0,6.0,8.0,8.0,7.0,8.0,5.0,7.0,7.0,8.0,6.0,7.0,8.0,9.0,7.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,7.0,7.0,6.0,9.0,7.0,8.0,6.0,6.0,99.0,7.0,7.0,6.0,99.0,8.0,NaN,NaN,NaN,NaN,NaN,8.0,1.0,6.0,1,5,1,5,"0,692541"
4,10409_CAL_VIDA_25Dist,19-sep-25,13:30:16,19-sep-25,13:45:40,0:15:24,1449663,20,1,4,3,10,7,10,9,7,9,10,9,10,8,9,6,7,7,9,5,99,9,99,4,10,10,8,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,9.0,6.0,6.0,6.0,8.0,10.0,10.0,99.0,8.0,5.0,8.0,9.0,9.0,8.0,9.0,10.0,10.0,10.0,9.0,9.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,7.0,8.0,8.0,8.0,10.0,10.0,8.0,99.0,9.0,9.0,99.0,99.0,99.0,10.0,NaN,NaN,NaN,NaN,NaN,8.0,6.0,1.0,1,5,4,1,"1,023298"

In [ ]:
#
df.shape

(8593, 135)

In [ ]:
# Visualización de las columnas del DataFrame
df.columns

Index(['estudio', 'FechaInicio', 'HoraInicio', 'FechaFin', 'HoraFin',
       'Duración', 'NúmeroEntrevista', 'DISTRITO',
       '(P0B*R1AE) - Sexo (anotar)', '(P0D*R1AS) - ¿Me puede decir su edad?',
       ...
       '(P17*R10S) - ¿Y en términos generales, en una escala de 0 a 10 ¿cómo calificaría usted la gestión que está realizando el equipo de gobierno del ayuntamiento de Madrid?',
       '(P18*R10S) - En una escala de 0 a 10, ¿cómo está de satisfecho/a con la administración del ayuntamiento de Madrid?',
       '(P19*R10S) - Poniendo en relación los impuestos que paga al ayuntamiento y los servicios que recibe. En una escala de 0 a 10 ¿cómo de satisfecho/a está?',
       '(P20*M2AS) - a - Primero', '(P20*M2AS) - b - Segundo',
       '(P21*R1AS) - Y para terminar, a efectos de analísis estadístico, voy a hacerle algunas preguntas. ¿Podría indicarme su nacionalidad?',
       '(P22*R1AE) - ¿Cuáles son los estudios de más alto nivel oficial que usted ha cursado (con independencia de que los haya terminado o no)?',
       '(P23*R1AS) - ¿En cuál de las siguientes situaciones se encuentra usted actualmente? situación principal.',
       '(P24*R1AE) - ¿Y podría decirme a qué partido o coalición votó en las elecciones municipales de mayo de 2023?',
       'Ponderacion'],
      dtype='str', length=135)

In [ ]:
# Eliminación de columnas irrelevantes
columnas_eliminar = ['estudio', 'HoraInicio', 'FechaFin', 'HoraFin', 'Duración', '(P1*M1AS) - a - En Madrid', '(P2*M10S) - a - En Madrid', 'Columna:  (P3*M10S) - a - En Madrid', '(P5A*R1AE) - ¿Cuáles son, a su juicio y por orden de prioridad, los tres problemas principales que existen actualmente en la ciudad de Madrid? (anotar 1ª problema)', 'Columna:  (P5B*R1AE) - Anotar 2ª problema', '(P5C*R1AE) - Anotar 3ª problema', 'P4_Total', 'Columna:  (P8*M10S) - o - La información y promoción turística', 'La organización de fiestas y eventos populares (cabalgata, fiestas de san isidro, fiestas de los distritos...)', '(P8*M10S) - s - La información al consumidor', 'Unnamed: 94', 'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', '(P10*R2AS) - Hablemos a continuación de cuestiones relativas a la movilidad y la seguridad en la ciudad  ¿qué medio o medios de transporte utiliza habitualmente para sus desplazamientos cotidianos (desplazamientos al lugar de trabajo, estudio u otros co']

In [ ]:
# Creación de un nuevo DataFrame sin las columnas irrelevantes
df_limpio = df.drop(columns=columnas_eliminar, errors='ignore')

In [ ]:
# Visualización de las primeras filas del DataFrame limpio
df_limpio.sample(10)

,FechaInicio,NúmeroEntrevista,DISTRITO,(P0B*R1AE) - Sexo (anotar),(P0D*R1AS) - ¿Me puede decir su edad?,"P0F*R1AS) - Actualmente, ¿está viviendo en...?",(P1*M1AS) - b - En su distrito,(P1*M1AS) - c - En su barrio,(P2*M10S) - b - En su distrito,(P2*M10S) - c - En su barrio,(P3*M10S) - a - En Madrid,(P3*M10S) - b - En su distrito,(P3*M10S) - c - En su barrio,(P4*M10S) - a - Cuidado y conservación de la ciudad,(P4*M10S) - b - Movilidad y transporte público,(P4*M10S) - c - Calidad medioambiental,(P4*M10S) - d - Facilidad para encontrar un trabajo,(P4*M10S) - e - Facilidad para emprender un negocio,(P4*M10S) - f - Imagen internacional de Madrid,(P4*M10S) - g - Coste de la vida,(P4*M10S) - h - Integración social,(P4*M10S) - i - Salud y servicios sanitarios,(P4*M10S) - j - Educación y centros educativos,(P4*M10S) - k - Facilidad para encontrar una vivienda en el marco de sus posibilidades,(P4*M10S) - l - Facilidad para hacer deporte,"(P4*M10S) - m - Oferta cultural, ocio y diversión",(P4*M10S) - n - Convivencia vecinal,(P4*M10S) - o - Seguridad,(P5B*R1AE) - Anotar 2ª problema,(P6*M10S) - a - Desigualdad de oportunidades entre hombres y mujeres,(P6*M10S) - b - Desigualdad de oportunidades entre la población extranjera y autóctona,(P7*M10S) - a - Las personas mayores,(P7*M10S) - b - La infancia,(P7*M10S) - c - Las personas con discapacidad,(P7*M10S) - d - Las personas lgtbiq+,(P7*M10S) - e - Los migrantes,(7*M10S) - f - La adolescencia,(P8*M10S) - a - La recogida de basuras y contenedores,"(P8*M10S) - b - La gestión y tratamiento de residuos (reciclaje, compostaje, etc.)",(P8*M10S) - c - El control de la contaminación atmosférica,(P8*M10S) - d - El control del ruido,(P8*M10S) - e - La limpieza de las calles,(P8*M10S) - f - El alumbrado público,"(P8*M10S) - g - Las infraestructuras de la ciudad para la circulación de vehículos (calles, túneles, etc.…)",(P8*M10S) - h - La pavimentación y conservación de las aceras,(P8*M10S) - i - El asfaltado y conservación de las calzadas,(P8*M10S) - j - La peatonalización de calles,"(P8*M10S) - k - La eliminación de barreras arquitectónicas (rebaje de bordillos, semáforos acústicos, etc.)",(P8*M10S) - l - La movilidad sostenible,(P8*M10S) - v - La mejora de la calidad del aire,(P8*M10S) - m - La conservación y rehabilitación de los edificios,(P8*M10S) - n - La protección de monumentos y del patrimonio histórico-artístico,(P8*M10S) - o - La información y promoción turística,"(P8*M10S) - p - La organización de fiestas y eventos populares (cabalgata, fiestas de san isidro, fiestas de los distritos...)","(P8*M10S) - q - El control de la salud pública (plagas, alimentos, aguas...)",(P8*M10S) - r - Las ayudas e incentivos a pymes y autónomos,(P8*M10S) - t - La promoción pública de viviendas,(P8*M10S) - w - La actuación frente a la ocupación ilegal,"(P8*M10S) - u - Los beneficios fiscales promovidos por el ayuntamiento (bajada de impuestos, bonificaciones...)",(P8*M10S) - x - El plan de fomento de la natalidad y la conciliación (el cheque bebé),(P9*M10S) - a - La atención a la ciudadanía,(P9*M10S) - c - El servicio de autobuses de la Emt,(P9*M10S) - d - Los taxis,(P9*M10S) - e - El ser (servicio de estacionamiento regulado),(P9*M10S) - f - Los agentes de movilidad,(P9*M10S) - g - La policía municipal,(P9*M10S) - h - Los bomberos,(P9*M10S) - i - Samur – protección civil,(P9*M10S) - j - La beca infantil para la escolarización 0-3 años,"(P9*M10S) - k - Los servicios sociales municipales (mayores, personas con discapacidad, inmigrantes, familias, …)",(P9*M10S) - l - Las vías ciclistas,(P9*M10S) - m - Los aparcamientos municipales,(P9*M10S) - n - Los puntos limpios de recogida y reciclaje de residuos,(P9*M10S) - o - Los espacios verdes (parques y jardines),(P9*M10S) - p - Los parques infantiles,(P9*M10S) - q - Los mercados municipales,(P9*M10S) - r - Las instalaciones deportivas municipales,(P9*M10S) - s - Los centros culturales municipales,(P9*M10S) - t - Las bibliotecas municipales,"(P9*M10S) - u - Los teatros municipales (Español, Matadero, Fernán Gómez…)",(P9*M10S) - v - El Samur social,(P9*M10S) - w - Bicimad,(P11*M10S) - b - Durante el día,(P11*M10S) - c - Durante la noche,(P11*M10S) - a - Y en general,(P12*M10S) - b - Durante el día,(P12*M10S) - c - Durante la noche,(P13*M10S) - b - Durante el día,(P13*M10S) - c - Durante la noche,"(P14*R10S) - Trataremos a continuación de la administración y el gobierno del ayuntamiento de Madrid en la misma escala, ¿en qué medida se considera usted informado/a de lo que hace el ayuntamiento de Madrid?",(P15*M10S) - a - Las oficinas de atención a la ciudadanía de línea Madrid,(P15*M10S) - b - El teléfono 010,(P15*M10S) - c - La web del ayuntamiento de Madrid: www.madrid.es,"(P15*M10S) - d - Aplicaciones del ayuntamiento para dispositivos móviles (app para móviles, Madrid móvil, emt Madrid…)",(P15*M10S) - e - Las oficinas de atención al contribuyente,(P15*M10S) - f - Chat on line de línea Madrid,"(P15*M10S) - g - Atención directa a las personas mayores, con número preferente y atención presencial sin cita previa",(P16*M10S) - a - Administración general del estado,(P16*M10S) - b - Administración de la comunidad de Madrid,(P16*M10S) - c - Administración del ayuntamiento de Madrid,"(P17*R10S) - ¿Y en términos generales, en una escala de 0 a 10 ¿cómo calificaría usted la gestión que está realizando el equipo de gobierno del ayuntamiento de Madrid?","(P18*R10S) - En una escala de 0 a 10, ¿cómo está de satisfecho/a con la administración del ayuntamiento de Madrid?",(P19*R10S) - Poniendo en relación los impuestos que paga al ayuntamiento y los servicios que recibe. En una escala de 0 a 10 ¿cómo de satisfecho/a está?,(P20*M2AS) - a - Primero,(P20*M2AS) - b - Segundo,"(P21*R1AS) - Y para terminar, a efectos de analísis estadístico, voy a hacerle algunas preguntas. ¿Podría indicarme su nacionalidad?",(P22*R1AE) - ¿Cuáles son los estudios de más alto nivel oficial que usted ha cursado (con independencia de que los haya terminado o no)?,(P23*R1AS) - ¿En cuál de las siguientes situaciones se encuentra usted actualmente? situación principal.,(P24*R1AE) - ¿Y podría decirme a qué partido o coalición votó en las elecciones municipales de mayo de 2023?,Ponderacion
4385,07-oct-25,1454044,9,1,2,1,8,9,7,8,5,5,5,8,7,4,8,4,7,9,8,5,99,2,8,7,9,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,9.0,6.0,99.0,7.0,99.0,99.0,99.0,99.0,0.0,99.0,5.0,7.0,99.0,5.0,8.0,7.0,99.0,6.0,99.0,3.0,9.0,6.0,7.0,10.0,8.0,10.0,8.0,5.0,8.0,9.0,5.0,4.0,99.0,4.0,99.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,11.0,1,6,1,1,"0,780617"
6583,20-oct-25,1456242,2,1,3,4,10,99,8,10,7,8,8,7,7,7,8,7,9,10,9,8,9,8,10,10,8,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,7.0,99.0,99.0,8.0,9.0,9.0,9.0,99.0,7.0,7.0,7.0,8.0,8.0,7.0,9.0,8.0,9.0,10.0,9.0,8.0,10.0,7.0,8.0,10.0,9.0,10.0,8.0,7.0,99.0,8.0,99.0,8.0,8.0,99.0,99.0,NaN,NaN,NaN,NaN,NaN,8.0,11.0,2.0,1,6,1,8,"0,725553"
184,22-sep-25,1449843,12,1,1,3,7,8,5,6,3,4,5,6,7,1,2,99,2,2,1,3,5,0,5,1,3,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,0.0,3.0,5.0,0.0,10.0,8.0,99.0,0.0,5.0,0.0,1.0,6.0,5.0,1.0,3.0,3.0,7.0,99.0,99.0,3.0,10.0,6.0,8.0,10.0,9.0,10.0,8.0,7.0,99.0,7.0,5.0,2.0,4.0,0.0,99.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,11.0,1,5,1,10,"1,484672"
1917,30-sep-25,1451576,5,2,2,4,7,7,6,7,2,3,4,6,10,5,8,1,10,0,6,2,9,1,10,10,99,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,10.0,10.0,8.0,8.0,10.0,10.0,10.0,6.0,9.0,99.0,9.0,10.0,8.0,5.0,7.0,7.0,99.0,10.0,9.0,9.0,99.0,4.0,2.0,5.0,7.0,2.0,5.0,6.0,1.0,9.0,99.0,9.0,9.0,99.0,99.0,9.0,NaN,NaN,NaN,NaN,NaN,1.0,4.0,8.0,1,6,1,8,"0,970158"
5499,13-oct-25,1455158,21,2,5,1,10,10,9,9,8,9,10,6,8,8,7,5,8,7,7,9,99,5,8,8,7,6,6.0,6.0,6.0,9.0,5.0,8.0,8.0,8.0,99.0,7.0,8.0,7.0,7.0,9.0,7.0,8.0,6.0,7.0,7.0,6.0,6.0,7.0,7.0,8.0,7.0,8.0,8.0,6.0,7.0,4.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,7.0,8.0,9.0,NaN,NaN,NaN,1,5,2,9,"0,252885"
2903,02-oct-25,1452562,12,2,1,2,6,5,6,5,5,5,5,9,9,8,4,8,5,4,8,8,7,3,10,7,6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,7.0,8.0,4.0,8.0,8.0,10.0,8.0,6.0,7.0,10.0,8.0,8.0,10.0,7.0,8.0,9.0,8.0,10.0,10.0,7.0,10.0,8.0,4.0,7.0,7.0,2.0,7.0,2.0,7.0,8.0,10.0,8.0,9.0,7.0,6.0,9.0,NaN,NaN,NaN,NaN,NaN,4.0,6.0,11.0,1,4,6,11,"1,170663"
2147,30-sep-25,1451806,8,1,5,1,8,8,7,7,5,5,5,4,7,4,4,4,6,3,5,4,4,2,6,7,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,5.0,5.0,8.0,7.0,9.0,6.0,99.0,5.0,5.0,5.0,8.0,4.0,99.0,5.0,5.0,4.0,7.0,5.0,8.0,5.0,7.0,4.0,5.0,8.0,4.0,8.0,4.0,6.0,6.0,7.0,7.0,7.0,6.0,7.0,99.0,NaN,NaN,NaN,NaN,NaN,3.0,6.0,5.0,1,5,1,3,"1,736503"
3836,04-oct-25,1453495,20,2,4,4,10,10,8,9,7,8,8,9,10,5,5,99,9,3,9,5,8,0,10,9,9,6,8.0,7.0,8.0,7.0,9.0,7.0,9.0,8.0,9.0,9.0,8.0,8.0,8.0,9.0,9.0,8.0,8.0,8.0,8.0,6.0,8.0,7.0,6.0,8.0,9.0,9.0,9.0,99.0,7.0,0.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,9.0,9.0,9.0,10.0,NaN,NaN,NaN,1,5,4,1,"0,950179"
63,20-sep-25,1449722,2,2,2,2,9,9,9,9,9,9,9,9,9,8,8,7,8,6,9,7,9,5,9,9,9,9,99.0,5.0,6.0,7.0,6.0,7.0,6.0,6.0,7.0,8.0,7.0,9.0,9.0,8.0,8.0,7.0,9.0,8.0,8.0,8.0,8.0,7.0,7.0,9.0,6.0,7.0,8.0,7.0,7.0,8.0,8.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,8.0,9.0,10.0,NaN,NaN,NaN,1,6,1,1,"0,882988"
8245,25-oct-25,1457904,3,1,5,4,10,10,9,9,6,6,6,7,10,7,9,99,10,3,8,7,10,0,10,10,5,8,10.0,2.0,2.0,7.0,7.0,7.0,6.0,6.0,3.0,8.0,8.0,8.0,5.0,6.0,8.0,10.0,6.0,7.0,8.0,3.0,99.0,99.0,99.0,10.0,8.0,9.0,8.0,99.0,0.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,8.0,7.0,7.0,7.0,NaN,NaN,NaN,1,6,2,1,"0,691864"

In [ ]:
# Información general del DataFrame limpio
df_limpio.info

<bound method DataFrame.info of      FechaInicio  NúmeroEntrevista  DISTRITO  (P0B*R1AE) - Sexo (anotar)  \
0      19-sep-25           1449659         2                           1
1      19-sep-25           1449660         4                           1
2      19-sep-25           1449661         8                           1
3      19-sep-25           1449662         5                           1
4      19-sep-25           1449663        20                           1
...          ...               ...       ...                         ...
8588   30-oct-25           1458247        21                           1
8589   30-oct-25           1458248        21                           2
8590   30-oct-25           1458249         9                           2
8591   30-oct-25           1458250         9                           2
8592   30-oct-25           1458251         9                           1

      (P0D*R1AS) - ¿Me puede decir su edad?  \
0                                         1
1                                         4
2                                         3
3                                         3
4                                         4
...                                     ...
8588                                      1
8589                                      2
8590                                      2
8591                                      2
8592                                      2

      P0F*R1AS) - Actualmente, ¿está viviendo en...?  \
0                                                  1
1                                                  1
2                                                  4
3                                                  4
4                                                  3
...                                              ...
8588                                               3
8589                                               5
8590                                               3
8591                                               4
8592                                               3

      (P1*M1AS) - b - En su distrito  (P1*M1AS) - c - En su barrio  \
0                                  9                             9
1                                  9                            10
2                                  8                             9
3                                  7                             8
4                                  7                            10
...                              ...                           ...
8588                              10                            10
8589                               6                             6
8590                               4                             2
8591                               8                             8
8592                              10                            10

      (P2*M10S) - b - En su distrito  (P2*M10S) - c - En su barrio  \
0                                  8                             9
1                                  9                             9
2                                  7                             8
3                                  7                             7
4                                  7                             9
...                              ...                           ...
8588                               8                             8
8589                               6                             6
8590                               6                             2
8591                               9                             8
8592                              10                            10

      (P3*M10S) - a - En Madrid  (P3*M10S) - b - En su distrito  \
0                             8                               9
1                            10                              10
2                             7                               8
3                             6                               9
4                            10                               9
...                         ...                             ...
8588                          4                               6
8589                          4                               6
8590                          4                               2
8591                          8                               8
8592                          8                              10

      (P3*M10S) - c - En su barrio  \
0                               10
1                               10
2                                9
3                                8
4                               10
...                            ...
8588                             6
8589                             6
8590                             0
8591                             8
8592                            10

      (P4*M10S) - a - Cuidado y conservación de la ciudad  \
0                                                     8
1                                                     8
2                                                     5
3                                                     7
4                                                     8
...                                                 ...
8588                                                  6
8589                                                  5
8590                                                  8
8591                                                  6
8592                                                  9

      (P4*M10S) - b - Movilidad y transporte público  \
0                                                 10
1                                                 10
2                                                  7
3                                                  8
4                                                  9
...                                              ...
8588                                               8
8589                                               7
8590                                              10
8591                                               8
8592                                               8

      (P4*M10S) - c - Calidad medioambiental  \
0                                          9
1                                          7
2                                          5
3                                          6
4                                          6
...                                      ...
8588                                       8
8589                                       7
8590                                       7
8591                                       5
8592                                       6

      (P4*M10S) - d - Facilidad para encontrar un trabajo  \
0                                                     8
1                                                     9
2                                                     5
3                                                     7
4                                                     7
...                                                 ...
8588                                                  9
8589                                                  4
8590                                                  8
8591                                                  8
8592                                                 10

      (P4*M10S) - e - Facilidad para emprender un negocio  \
0                                                    99
1                                                     9
2                                                     5
3                                                     6
4                                                     7
...                                                 ...
8588                                                 99
8589                                                  5
8590                                                  5
8591                                                  3
8592                                                 10

      (P4*M10S) - f - Imagen internacional de Madrid  \
0                                                  9
1                                                 10
2                                                  8
3                                                  8
4                                                  9
...                                              ...
8588                                              10
8589                                               9
8590                                               9
8591                                               8
8592                                              10

      (P4*M10S) - g - Coste de la vida  (P4*M10S) - h - Integración social  \
0                                    5                                   8
1                                    7                                   8
2                                    5                                   7
3                                    9                                   7
4                                    5                                  99
...                                ...                                 ...
8588                                 4                                   7
8589                                 0                                   3
8590                                 0                                   7
8591                                 5                                   8
8592                                 7                                   9

      (P4*M10S) - i - Salud y servicios sanitarios  \
0                                                8
1                                                8
2                                                5
3                                                7
4                                                9
...                                            ...
8588                                             8
8589                                             5
8590                                             4
8591                                             8
8592                                             9

      (P4*M10S) - j - Educación y centros educativos  \
0                                                  8
1                                                  8
2                                                  7
3                                                  7
4                                                 99
...                                              ...
8588                                              99
8589                                               3
8590                                               7
8591                                               8
8592                                               8

      (P4*M10S) - k - Facilidad para encontrar una vivienda en el marco de sus posibilidades  \
0                                                     4
1                                                     7
2                                                     2
3                                                     7
4                                                     4
...                                                 ...
8588                                                  3
8589                                                  1
8590                                                  2
8591                                                  4
8592                                                  0

      (P4*M10S) - l - Facilidad para hacer deporte  \
0                                               10
1                                                9
2                                                7
3                                                7
4                                               10
...                                            ...
8588                                            10
8589                                             6
8590                                             9
8591                                             8
8592                                            10

      (P4*M10S) - m - Oferta cultural, ocio y diversión  \
0                                                    10
1                                                    10
2                                                     8
3                                                     7
4                                                    10
...                                                 ...
8588                                                 10
8589                                                 10
8590                                                 10
8591                                                  8
8592                                                 10

      (P4*M10S) - n - Convivencia vecinal  (P4*M10S) - o - Seguridad  \
0                                       7                          9
1                                       7                          8
2                                       7                          7
3                                       7                          7
4                                       8                          7
...                                   ...                        ...
8588                                    6                          7
8589                                    4                          5
8590                                    8                          8
8591                                    5                          5
8592                                   10                         10

      (P5B*R1AE) - Anotar 2ª problema  \
0                                97.0
1                                 NaN
2                                 8.0
3                                 NaN
4                                 NaN
...                               ...
8588                              NaN
8589                              NaN
8590                              8.0
8591                              9.0
8592                              1.0

      (P6*M10S) - a - Desigualdad de oportunidades entre hombres y mujeres  \
0                                                   7.0
1                                                   NaN
2                                                   7.0
3                                                   NaN
4                                                   NaN
...                                                 ...
8588                                                NaN
8589                                                NaN
8590                                                2.0
8591                                                5.0
8592                                                0.0

      (P6*M10S) - b - Desigualdad de oportunidades entre la población extranjera y autóctona  \
0                                                   7.0
1                                                   NaN
2                                                   7.0
3                                                   NaN
4                                                   NaN
...                                                 ...
8588                                                NaN
8589                                                NaN
8590                                                6.0
8591                                                5.0
8592                                                3.0

      (P7*M10S) - a - Las personas mayores  (P7*M10S) - b - La infancia  \
0                                      8.0                          8.0
1                                      NaN                          NaN
2                                      5.0                          5.0
3                                      NaN                          NaN
4                                      NaN                          NaN
...                                    ...                          ...
8588                                   NaN                          NaN
8589                                   NaN                          NaN
8590                                   8.0                          6.0
8591                                   8.0                          8.0
8592                                   7.0                         10.0

      (P7*M10S) - c - Las personas con discapacidad  \
0                                               7.0
1                                               NaN
2                                               5.0
3                                               NaN
4                                               NaN
...                                             ...
8588                                            NaN
8589                                            NaN
8590                                            7.0
8591                                            8.0
8592                                           10.0

      (P7*M10S) - d - Las personas lgtbiq+  (P7*M10S) - e - Los migrantes  \
0                                      8.0                            7.0
1                                      NaN                            NaN
2                                      7.0                            5.0
3                                      NaN                            NaN
4                                      NaN                            NaN
...                                    ...                            ...
8588                                   NaN                            NaN
8589                                   NaN                            NaN
8590                                   7.0                            7.0
8591                                   8.0                            5.0
8592                                  10.0                           10.0

      (7*M10S) - f - La adolescencia  \
0                                8.0
1                                NaN
2                                8.0
3                                NaN
4                                NaN
...                              ...
8588                             NaN
8589                             NaN
8590                             6.0
8591                             8.0
8592                            10.0

      (P8*M10S) - a - La recogida de basuras y contenedores  \
0                                                   8.0
1                                                   NaN
2                                                   6.0
3                                                   NaN
4                                                   NaN
...                                                 ...
8588                                                NaN
8589                                                NaN
8590                                                5.0
8591                                                8.0
8592                                                8.0

      (P8*M10S) - b - La gestión y tratamiento de residuos (reciclaje, compostaje, etc.)  \
0                                                   8.0
1                                                   NaN
2                                                   5.0
3                                                   NaN
4                                                   NaN
...                                                 ...
8588                                                NaN
8589                                                NaN
8590                                                2.0
8591                                                5.0
8592                                                7.0

      (P8*M10S) - c - El control de la contaminación atmosférica  \
0                                                   7.0

In [ ]:
# lista de columnas adicionales a eliminar
lista_eliminar_2 = ['(P11*M10S) - a - Y en general', '(P12*M10S) - b - Durante el día', '(P12*M10S) - c - Durante la noche', '(P14*R10S) - Trataremos a continuación de la administración y el gobierno del ayuntamiento de Madrid  en la misma escala, ¿en qué medida se considera usted  informado/a  de lo que hace el ayuntamiento de Madrid?', '(P15*M10S) - a - Las oficinas de atención a la ciudadanía de línea Madrid', '(P15*M10S) - b - El teléfono 010', '(P15*M10S) - c - La web del ayuntamiento de Madrid: www.madrid.es', '(P15*M10S) - d - Aplicaciones del ayuntamiento para dispositivos móviles (app para móviles, Madrid móvil, emt Madrid…)', '(P15*M10S) - e - Las oficinas de atención al contribuyente', '(P15*M10S) - f - Chat on line de línea Madrid', '(P15*M10S) - g - Atención directa a las personas mayores, con número preferente y atención presencial sin cita previa', '(P16*M10S) - a - Administración general del estado', '(P16*M10S) - b - Administración de la comunidad de Madrid', '(P16*M10S) - c - Administración del ayuntamiento de Madrid', '(P17*R10S) - ¿Y en términos generales, en una escala de 0 a 10 ¿cómo calificaría usted la gestión que está realizando el equipo de gobierno del ayuntamiento de Madrid?', '(P18*R10S) - En una escala de 0 a 10, ¿cómo está de satisfecho/a con la administración del ayuntamiento de Madrid?', '(P19*R10S) - Poniendo en relación los impuestos que paga al ayuntamiento y los servicios que recibe. En una escala de 0 a 10 ¿cómo de satisfecho/a está?', '(P20*M2AS) - a - Primero', ' (P20*M2AS) - b - Segundo', '(P21*R1AS) - Y para terminar, a efectos de analísis estadístico, voy a hacerle algunas preguntas. ¿Podría indicarme su nacionalidad?', '(P22*R1AE) - ¿Cuáles son los estudios de más alto nivel oficial que usted ha cursado (con independencia de que los haya terminado o no)?', '(P23*R1AS) - ¿En cuál de las siguientes situaciones se encuentra usted actualmente? situación principal.', '(P24*R1AE) - ¿Y podría decirme a qué partido o coalición votó en las elecciones municipales de mayo de 2023?', 'Columna:  Ponderacion']

In [ ]:
# Creación de un nuevo DataFrame sin las columnas adicionales
df_limpio2 = df_limpio.drop(columns=lista_eliminar_2, errors='ignore')

In [ ]:
# Visualización de la forma del DataFrame limpio
df_limpio2.shape

(8593, 88)

In [15]:
df_limpio2.head()

,FechaInicio,NúmeroEntrevista,DISTRITO,(P0B*R1AE) - Sexo (anotar),(P0D*R1AS) - ¿Me puede decir su edad?,"P0F*R1AS) - Actualmente, ¿está viviendo en...?",(P1*M1AS) - b - En su distrito,(P1*M1AS) - c - En su barrio,(P2*M10S) - b - En su distrito,(P2*M10S) - c - En su barrio,(P3*M10S) - a - En Madrid,(P3*M10S) - b - En su distrito,(P3*M10S) - c - En su barrio,(P4*M10S) - a - Cuidado y conservación de la ciudad,(P4*M10S) - b - Movilidad y transporte público,(P4*M10S) - c - Calidad medioambiental,(P4*M10S) - d - Facilidad para encontrar un trabajo,(P4*M10S) - e - Facilidad para emprender un negocio,(P4*M10S) - f - Imagen internacional de Madrid,(P4*M10S) - g - Coste de la vida,(P4*M10S) - h - Integración social,(P4*M10S) - i - Salud y servicios sanitarios,(P4*M10S) - j - Educación y centros educativos,(P4*M10S) - k - Facilidad para encontrar una vivienda en el marco de sus posibilidades,(P4*M10S) - l - Facilidad para hacer deporte,"(P4*M10S) - m - Oferta cultural, ocio y diversión",(P4*M10S) - n - Convivencia vecinal,(P4*M10S) - o - Seguridad,(P5B*R1AE) - Anotar 2ª problema,(P6*M10S) - a - Desigualdad de oportunidades entre hombres y mujeres,(P6*M10S) - b - Desigualdad de oportunidades entre la población extranjera y autóctona,(P7*M10S) - a - Las personas mayores,(P7*M10S) - b - La infancia,(P7*M10S) - c - Las personas con discapacidad,(P7*M10S) - d - Las personas lgtbiq+,(P7*M10S) - e - Los migrantes,(7*M10S) - f - La adolescencia,(P8*M10S) - a - La recogida de basuras y contenedores,"(P8*M10S) - b - La gestión y tratamiento de residuos (reciclaje, compostaje, etc.)",(P8*M10S) - c - El control de la contaminación atmosférica,(P8*M10S) - d - El control del ruido,(P8*M10S) - e - La limpieza de las calles,(P8*M10S) - f - El alumbrado público,"(P8*M10S) - g - Las infraestructuras de la ciudad para la circulación de vehículos (calles, túneles, etc.…)",(P8*M10S) - h - La pavimentación y conservación de las aceras,(P8*M10S) - i - El asfaltado y conservación de las calzadas,(P8*M10S) - j - La peatonalización de calles,"(P8*M10S) - k - La eliminación de barreras arquitectónicas (rebaje de bordillos, semáforos acústicos, etc.)",(P8*M10S) - l - La movilidad sostenible,(P8*M10S) - v - La mejora de la calidad del aire,(P8*M10S) - m - La conservación y rehabilitación de los edificios,(P8*M10S) - n - La protección de monumentos y del patrimonio histórico-artístico,(P8*M10S) - o - La información y promoción turística,"(P8*M10S) - p - La organización de fiestas y eventos populares (cabalgata, fiestas de san isidro, fiestas de los distritos...)","(P8*M10S) - q - El control de la salud pública (plagas, alimentos, aguas...)",(P8*M10S) - r - Las ayudas e incentivos a pymes y autónomos,(P8*M10S) - t - La promoción pública de viviendas,(P8*M10S) - w - La actuación frente a la ocupación ilegal,"(P8*M10S) - u - Los beneficios fiscales promovidos por el ayuntamiento (bajada de impuestos, bonificaciones...)",(P8*M10S) - x - El plan de fomento de la natalidad y la conciliación (el cheque bebé),(P9*M10S) - a - La atención a la ciudadanía,(P9*M10S) - c - El servicio de autobuses de la Emt,(P9*M10S) - d - Los taxis,(P9*M10S) - e - El ser (servicio de estacionamiento regulado),(P9*M10S) - f - Los agentes de movilidad,(P9*M10S) - g - La policía municipal,(P9*M10S) - h - Los bomberos,(P9*M10S) - i - Samur – protección civil,(P9*M10S) - j - La beca infantil para la escolarización 0-3 años,"(P9*M10S) - k - Los servicios sociales municipales (mayores, personas con discapacidad, inmigrantes, familias, …)",(P9*M10S) - l - Las vías ciclistas,(P9*M10S) - m - Los aparcamientos municipales,(P9*M10S) - n - Los puntos limpios de recogida y reciclaje de residuos,(P9*M10S) - o - Los espacios verdes (parques y jardines),(P9*M10S) - p - Los parques infantiles,(P9*M10S) - q - Los mercados municipales,(P9*M10S) - r - Las instalaciones deportivas municipales,(P9*M10S) - s - Los centros culturales municipales,(P9*M10S) - t - Las bibliotecas municipales,"(P9*M10S) - u - Los teatros municipales (Español, Matadero, Fernán Gómez…)",(P9*M10S) - v - El Samur social,(P9*M10S) - w - Bicimad,(P11*M10S) - b - Durante el día,(P11*M10S) - c - Durante la noche,(P13*M10S) - b - Durante el día,(P13*M10S) - c - Durante la noche,(P20*M2AS) - b - Segundo,Ponderacion
0,19-sep-25,1449659,2,1,1,1,9,9,8,9,8,9,10,8,10,9,8,99,9,5,8,8,8,4,10,10,7,9,97.0,7.0,7.0,8.0,8.0,7.0,8.0,7.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,9.0,7.0,8.0,8.0,7.0,8.0,7.0,7.0,8.0,8.0,7.0,7.0,9.0,5.0,8.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,236126"
1,19-sep-25,1449660,4,1,4,1,9,10,9,9,10,10,10,8,10,7,9,9,10,7,8,8,8,7,9,10,7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,10.0,8.0,9.0,8.0,8.0,10.0,9.0,9.0,8.0,7.0,9.0,9.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,9.0,99.0,9.0,7.0,9.0,9.0,6.0,"0,787242"
2,19-sep-25,1449661,8,1,3,4,8,9,7,8,7,8,9,5,7,5,5,5,8,5,7,5,7,2,7,8,7,7,8.0,7.0,7.0,5.0,5.0,5.0,7.0,5.0,8.0,6.0,5.0,5.0,5.0,5.0,5.0,6.0,2.0,2.0,5.0,5.0,5.0,5.0,5.0,7.0,8.0,7.0,5.0,6.0,2.0,2.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,270241"
3,19-sep-25,1449662,5,1,3,4,7,8,7,7,6,9,8,7,8,6,7,6,8,9,7,7,7,7,7,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,6.0,8.0,7.0,8.0,7.0,6.0,8.0,8.0,7.0,8.0,5.0,7.0,7.0,8.0,6.0,7.0,8.0,9.0,7.0,5.0,8.0,7.0,7.0,8.0,6.0,"0,692541"
4,19-sep-25,1449663,20,1,4,3,7,10,7,9,10,9,10,8,9,6,7,7,9,5,99,9,99,4,10,10,8,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,9.0,6.0,6.0,6.0,8.0,10.0,10.0,99.0,8.0,5.0,8.0,9.0,9.0,8.0,9.0,10.0,10.0,10.0,9.0,9.0,5.0,9.0,7.0,10.0,10.0,1.0,"1,023298"

In [ ]:
# Guardar el DataFrame limpio en un nuevo archivo CSV
df_limpio2.to_csv('csv_calidaddevida.csv', index=False)